# Generated by Django 4.1.7 on 2023-03-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="bannel_title",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
